apiVersion: app2/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: app2-namespace
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: kubeapp2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8891 # порт, на котором работает приложение