apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: kubeapp1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8890 # порт, на котором работает приложение
---
kind: Service
apiVersion: v1
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 8080 # порт, который торчит наружу из сервиса, который мы будем передавать в ingress
    targetPort: 8890 # порт, который слушает сервис, на котором работает наше приложение
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  annotations: 
    ingress.kubernetes.io/ssl-redicrect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-service
            port:
              number: 8080 # порт, который слушает ingress и прокидывает наружу. По дефолту ингресс прокидывает наружу 80 порт